language: csharp
dist: xenial
mono: none
dotnet: 3.1
jobs:
  include:
    - stage: "Build"
      if: branch != master OR branch != docs
      solution: "./src/DotNetStac.sln"
      install: dotnet restore src/
      script: dotnet build src/
    - stage: "Generate Documentation"
      if: branch = master OR branch = docs
      install:
        - dotnet restore
        - nuget install docfx.console -Version 2.51.0
      script:
        - ./docfx.console.2.51.0/tools/docfx.exe metadata docfx_project/docfx.json
        - ./docfx.console.2.51.0/tools/docfx.exe build docfx_project/docfx.json
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: docs/_site
        on:
          branch: master
    - stage: "Run Tests"
      if: branch != master OR branch != docs
      install: dotnet restore
      script: dotnet test src/DotNetStac.Test/DotNetStac.Test.csproj --verbosity detailed
    - stage: "Publish to NuGet"
      if: branch = master
      install: dotnet restore
      script: 
        - dotnet build
        - dotnet publish -c release
        - dotnet pack -c release --include-symbols -o publish
        - dotnet nuget push publish/*.nupkg --skip-duplicate -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json