name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' #${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src --configuration Release --no-restore
      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" --settings:src/DotNetStac.Test/coverlet.runsettings --results-directory:TestResults src
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: TestResults
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: docs/docfx.json
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results #-${{ matrix.dotnet-version }}
          path: TestResults #-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
        # Publish generated site using GitHub Pages
    